//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EzSpice.rc
//
#define IDCANCEL                        2
#define ID_USER_EDIT_HELP               3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_RIBBON_STATE                101
#define IDS_RIBBON_GRIDVIEW             102
#define IDS_RIBBON_NEWWINDOW            103
#define IDS_RIBBON_DOCKING              104
#define IDS_RIBBON_ELEMENTPANE          105
#define IDS_RIBBON_OUTPUTPANE           106
#define IDS_RIBBON_ELEMENTTREEVIEW      107
#define IDS_RIBBON_SETTING              108
#define IDS_RIBBON_ELEMENTSETTING       109
#define IDB_WRITESMALL                  110
#define IDS_RIBBON_USERSETTING          110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_EzSpiceTYPE                 130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDS_RIBBON_NEWELEMENT           310
#define IDS_RIBBON_SIMULATION           311
#define IDS_RIBBON_VIRTUALDEVICE        312
#define IDS_RIBBON_REDO                 313
#define IDS_RIBBON_UNDO                 314
#define IDS_RIBBON_INCREASE             315
#define IDS_RIBBON_DECREASE             316
#define IDS_RIBBON_OPERATION            317
#define IDS_RIBBON_SINGLEPROV           318
#define IDS_RIBBON_OSCILOSCOPE          319
#define IDS_RIBBON_MULTIMETER           320
#define IDS_RIBBON_FUNCTION             321
#define IDS_RIBBON_POWERSUPPLY          322
#define IDS_RIBBON_DIRECTSEARCH         323
#define IDS_RIBBON_DETAILSEARCH         324
#define IDS_RIBBON_MULTPROV             325
#define IDS_RIBBON_LINK                 326
#define IDS_RIBBON_SHOW                 327
#define IDS_RIBBON_DECIDE               328
#define IDB_PNG1                        329
#define IDS_RIBBON_GROUND               329
#define IDB_PNG2                        330
#define IDR_HTML_ELEMENTEDITDLG         331
#define IDD_ELEMENTDLG                  332
#define IDR_HTML_NETWORKTHEORY          333
#define IDI_ICON1                       334
#define IDI_ICON2                       335
#define IDI_ICON3                       336
#define IDI_ICON4                       337
#define IDR_MENU1                       338
#define IDD_DIALOG1                     339
#define IDD_ELEMENTEDITDLG              339
#define IDD_ELEMENTSEARCH               340
#define IDD_DIALOG2                     341
#define IDD_GROUPINSERT                 341
#define IDB_BITMAP2                     342
#define IDB_TESTBITMAP                  342
#define IDD_SIMULDLG                    343
#define IDD_MULTMITER                   344
#define IDB_MENULARGE                   346
#define IDB_BITMAP5                     347
#define IDB_MENUSMALL                   347
#define IDD_DIALOG3                     348
#define IDD_RESULT                      348
#define IDB_PNG3                        349
#define IDB_PNG4                        352
#define IDB_MLARGE                      354
#define IDB_BITMAP1                     358
#define IDB_SMALL                       358
#define IDB_BITMAP3                     359
#define IDB_ELEMENT                     359
#define IDD_TRANSIENT                   360
#define IDR_MENU2                       361
#define IDR_SIMUAL_MENU                 361
#define IDB_BITMAP4                     362
#define IDB_EZMAIN                      362
#define IDD_DIALOG4                     363
#define IDD_NETWORKTHEROY               363
#define IDB_THEROY1                     364
#define IDB_THEROY2                     365
#define IDB_THEROY3                     366
#define IDB_THEROY4                     367
#define IDB_THEROY5                     368
#define IDB_THEROY6                     369
#define IDD_FUNC                        370
#define IDD_DIALOG5                     371
#define IDD_POWER                       371
#define IDB_PNG5                        372
#define IDB_BITMAP6                     374
#define IDB_RESIS                       374
#define IDD_DIALOG6                     375
#define IDD_HELPLE                      375
#define IDC_LISTCTRL                    1001
#define IDC_USERGROUP                   1002
#define IDC_INSERT                      1003
#define IDC_DELETE                      1004
#define IDC_ELEMENTGROUP                1006
#define IDC_ELEMENTLIST                 1007
#define IDC_ELEMENTINFO                 1008
#define IDC_GROUPLISTDISPLAY            1009
#define ID_USER_EDIT_OK                 1010
#define ID_USER_EDIT_CANCEL             1011
#define IDC_GROUPDISPLAY                1012
#define IDC_USER_OK                     1013
#define IDC_USER_CANCEL                 1014
#define IDC_USER_HLEP                   1015
#define IDC_SEARCH                      1015
#define IDC_FILTER1                     1016
#define IDC_FILTER2                     1017
#define IDC_ELEMENTLIST2                1018
#define IDC_FILTER3                     1018
#define IDC_SEARCHLIST                  1019
#define IDC_SEARCH_INSERT               1020
#define IDC_SEARCH_CLOSE                1021
#define IDC_SEARCHEDIT                  1022
#define IDC_EDIT1                       1023
#define IDC_LIST1                       1024
#define IDC_SIMULSTRING                 1024
#define IDC_EDIT2                       1024
#define IDC_CONTENT                     1024
#define IDC_TOTALCOUNT                  1025
#define IDC_INFOTAB                     1027
#define IDC_ZOONIN                      1028
#define IDC_ZOOMOUT                     1032
#define IDC_MODIFICATION                1033
#define IDC_PLOTTER                     1034
#define IDC_RADIO1                      1036
#define IDC_RESULT                      1036
#define IDC_GROUP_CONTROL               1037
#define IDC_GROUP_SIMUL                 1038
#define IDC_GROUP_WAVE                  1039
#define IDC_MULTIMETERVIEW              1040
#define IDC_AC_ELECTRIC                 1041
#define IDC_DC_VOLTAGE                  1042
#define IDC_MULTCOMBO                   1043
#define IDC_BUTTON1                     1044
#define IDC_BUTTON3                     1045
#define IDC_OHM                         1045
#define IDC_LEFT                        1045
#define IDC_AC_VOLTAGE                  1046
#define IDC_RIGHT                       1046
#define IDC_BUTTON2                     1047
#define IDC_EDIT                        1047
#define IDC_DC_ELECTRIC                 1048
#define IDC_BUTTON4                     1049
#define IDC_SEC                         1051
#define IDC_SIGN                        1051
#define IDC_VOLT                        1052
#define IDC_SQUA                        1052
#define ID_TR_HELP                      1053
#define IDC_THEROYPICTURE               1054
#define IDC_TRIA                        1054
#define IDC_SPIN                        1055
#define IDC_HZ                          1058
#define IDC_SEND                        1059
#define IDC_SUBSTRING                   1059
#define IDC_TREE                        1061
#define IDC_EXAPLE                      1061
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_32771                        32771
#define ID_GRIDLINE                     32772
#define ID_USER_GRIDLINE                32773
#define ID_32774                        32774
#define ID_32775                        32775
#define ID_32776                        32776
#define ID_USER_SENDMAIL                32777
#define ID_USER_NOTEPED                 32778
#define ID_USER_VISITSITE               32779
#define ID_32780                        32780
#define ID_32781                        32781
#define ID_32782                        32782
#define ID_32783                        32783
#define ID_USER_DEVICE_OSCIL            32784
#define ID_USER_DEVICE_                 32785
#define ID_USER_DEVICE_DISIT            32786
#define ID_USER_DEVICE_FUNC             32787
#define ID_USER_DEVICE_POWER            32788
#define ID_32789                        32789
#define ID_32790                        32790
#define ID_32791                        32791
#define ID_32792                        32792
#define ID_USER_STATE_REDO              32793
#define ID_USER_STATE_UNDO              32794
#define ID_USER_STATE_                  32795
#define ID_USER_STATE_INCREASE          32796
#define ID_USER_STATE_DECREASE          32797
#define ID_32798                        32798
#define ID_ACCELERATOR32800             32800
#define ID_32802                        32802
#define ID_32803                        32803
#define ID_32804                        32804
#define ID_USER_DOCKING_ELETREEVIEW     32805
#define ID_USER_DOCKING                 32806
#define ID_USER_DOCKING_OUTPUTVIEW      32807
#define ID_USER_DOCKING_ELEVIEW         32808
#define ID_32809                        32809
#define ID_USER_ELEMENT_EDITDLG         32810
#define ID_32811                        32811
#define ID_32812                        32812
#define ID_USER_SRARCH_DETAIL           32813
#define ID_USER_SEARCH_DIRECT           32814
#define ID_32815                        32815
#define ID_32816                        32816
#define ID_32817                        32817
#define ID_USER_Simul                   32818
#define ID_USER_SIMUL_START             32819
#define ID_USER_SIMUL_PROV1             32820
#define ID_USER_SIMUL_PROV2             32821
#define ID_32822                        32822
#define ID_32825                        32825
#define ID_JUCTION                      32826
#define ID_JUNCTION                     32827
#define ID_32828                        32828
#define ID_32829                        32829
#define ID_DECIDE                       32830
#define ID_GROUND                       32831
#define ID_32832                        32832
#define ID_32833                        32833
#define ID_USER_SAVE                    32834
#define ID_USER_                        32835
#define ID_USER_OPEN                    32836
#define ID_32837                        32837
#define ID_USER_SAVE_AS                 32838
#define ID_32839                        32839
#define ID_EDIT_TRANSIENT               32840
#define ID_32841                        32841
#define ID_USER_MATH                    32842
#define ID_32843                        32843
#define ID_SIMUAL_SETTING               32844
#define ID_32845                        32845
#define ID_USER_LINENUMBERpBtnLineNumber 32846
#define ID_USER_LINENUMBER              32847

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        376
#define _APS_NEXT_COMMAND_VALUE         32848
#define _APS_NEXT_CONTROL_VALUE         1062
#define _APS_NEXT_SYMED_VALUE           334
#endif
#endif
